### ISSUE TITLE
Error running test

### ISSUE THREAD

**Issue by marina-manrique** [ohnosequences-bundles/spades#2]
Hi again @laughedelic !

Now I'm getting this error when I run `test`

``` bash
[info] ApplicationTest:
[info] - Apply spades bundle to an instance *** FAILED ***
[info]   com.amazonaws.AmazonServiceException: The instance ID 'i-83c99e64' does not exist (Service: AmazonEC2; Status Code: 400; Error Code: InvalidInstanceID.NotFound; Request ID: ff649f32-3ce4-4990-8873-d001ff9beea2)
[info]   at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:1078)
[info]   at com.amazonaws.http.AmazonHttpClient.executeOneRequest(AmazonHttpClient.java:726)
[info]   at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:461)
[info]   at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:296)
[info]   at com.amazonaws.services.ec2.AmazonEC2Client.invoke(AmazonEC2Client.java:10549)
[info]   at com.amazonaws.services.ec2.AmazonEC2Client.createTags(AmazonEC2Client.java:6273)
[info]   at ohnosequences.awstools.ec2.EC2.createTags(EC2.scala:313)
[info]   at ohnosequences.awstools.ec2.EC2$Instance.createTag(EC2.scala:82)
[info]   at ohnosequences.statika.cli.StatikaEC2$StatikaEC2Tools$$anonfun$applyAndWait$1.apply(StatikaEC2.scala:43)
[info]   at ohnosequences.statika.cli.StatikaEC2$StatikaEC2Tools$$anonfun$applyAndWait$1.apply(StatikaEC2.scala:37)
[info]   ...
[info] Run completed in 3 seconds, 671 milliseconds.
[info] Total number of tests run: 1
[info] Suites: completed 1, aborted 0
[info] Tests: succeeded 0, failed 1, canceled 0, ignored 0, pending 0
[info] *** 1 TEST FAILED ***
[error] Failed tests:
[error]     ohnosequences.statika.tests.ApplicationTest
[error] (test:test) sbt.TestsFailedException: Tests unsuccessful
[error] Total time: 6 s, completed Apr 9, 2015 11:32:19 AM
1. Waiting for source changes... (press enter to interrupt)

```

**Comment by laughedelic** [comment]
It was about permissions. Closing

**Comment by marina-manrique** [comment]
it was an issue with the configuration of my aws credentials, closing this
